CREATE TABLE dbo.Logs(
	Id INT PRIMARY KEY IDENTITY (1,1),
	[Date] DATETIME NOT NULL,
	[Level] NVARCHAR(256) NOT NULL,
	[Message] NVARCHAR(MAX) NOT NULL,
	MachineName NVARCHAR(300) NOT NULL,
	Logger NVARCHAR(300) NOT NULL
)