// <auto-generated />
using System;
using DGII.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DGII.DAL.Migrations
{
    [DbContext(typeof(DGIIContext))]
    partial class DGIIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DGII.BOL.Models.Comprobante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContribuyenteId")
                        .HasColumnType("int");

                    b.Property<decimal>("Itbis18")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ncf")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime>("fechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("rncCedula")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("Ncf")
                        .IsUnique();

                    b.HasIndex("ContribuyenteId", "rncCedula");

                    b.ToTable("Comprobantes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContribuyenteId = 1,
                            Itbis18 = 36m,
                            Monto = 200m,
                            Ncf = "E310000000001",
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            rncCedula = "98754321012"
                        },
                        new
                        {
                            Id = 2,
                            ContribuyenteId = 1,
                            Itbis18 = 180m,
                            Monto = 1000m,
                            Ncf = "E310000000002",
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            rncCedula = "98754321012"
                        },
                        new
                        {
                            Id = 3,
                            ContribuyenteId = 1,
                            Itbis18 = 36m,
                            Monto = 200m,
                            Ncf = "E310000000003",
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            rncCedula = "98754321012"
                        },
                        new
                        {
                            Id = 4,
                            ContribuyenteId = 1,
                            Itbis18 = 180m,
                            Monto = 1000m,
                            Ncf = "E310000000004",
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            rncCedula = "98754321012"
                        },
                        new
                        {
                            Id = 5,
                            ContribuyenteId = 1,
                            Itbis18 = 36m,
                            Monto = 200m,
                            Ncf = "E310000000005",
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            rncCedula = "98754321012"
                        },
                        new
                        {
                            Id = 6,
                            ContribuyenteId = 1,
                            Itbis18 = 180m,
                            Monto = 1000m,
                            Ncf = "E310000000006",
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            rncCedula = "98754321012"
                        },
                        new
                        {
                            Id = 7,
                            ContribuyenteId = 1,
                            Itbis18 = 36m,
                            Monto = 200m,
                            Ncf = "E310000000007",
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            rncCedula = "98754321012"
                        },
                        new
                        {
                            Id = 8,
                            ContribuyenteId = 2,
                            Itbis18 = 180m,
                            Monto = 1000m,
                            Ncf = "E310000000008",
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            rncCedula = "123456789"
                        },
                        new
                        {
                            Id = 9,
                            ContribuyenteId = 2,
                            Itbis18 = 36m,
                            Monto = 200m,
                            Ncf = "E310000000009",
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            rncCedula = "123456789"
                        },
                        new
                        {
                            Id = 10,
                            ContribuyenteId = 2,
                            Itbis18 = 180m,
                            Monto = 1000m,
                            Ncf = "E310000000010",
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            rncCedula = "123456789"
                        },
                        new
                        {
                            Id = 11,
                            ContribuyenteId = 2,
                            Itbis18 = 36m,
                            Monto = 200m,
                            Ncf = "E310000000011",
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            rncCedula = "123456789"
                        },
                        new
                        {
                            Id = 12,
                            ContribuyenteId = 2,
                            Itbis18 = 180m,
                            Monto = 1000m,
                            Ncf = "E310000000012",
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            rncCedula = "123456789"
                        },
                        new
                        {
                            Id = 13,
                            ContribuyenteId = 3,
                            Itbis18 = 180m,
                            Monto = 1000m,
                            Ncf = "E310000000013",
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            rncCedula = "123876879"
                        },
                        new
                        {
                            Id = 14,
                            ContribuyenteId = 3,
                            Itbis18 = 36m,
                            Monto = 200m,
                            Ncf = "E310000000014",
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            rncCedula = "123876879"
                        },
                        new
                        {
                            Id = 15,
                            ContribuyenteId = 3,
                            Itbis18 = 180m,
                            Monto = 1000m,
                            Ncf = "E310000000015",
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            rncCedula = "123876879"
                        },
                        new
                        {
                            Id = 16,
                            ContribuyenteId = 3,
                            Itbis18 = 36m,
                            Monto = 200m,
                            Ncf = "E310000000016",
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            rncCedula = "123876879"
                        },
                        new
                        {
                            Id = 17,
                            ContribuyenteId = 3,
                            Itbis18 = 180m,
                            Monto = 1000m,
                            Ncf = "E310000000017",
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            rncCedula = "123876879"
                        },
                        new
                        {
                            Id = 18,
                            ContribuyenteId = 3,
                            Itbis18 = 36m,
                            Monto = 200m,
                            Ncf = "E310000000018",
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            rncCedula = "123876879"
                        },
                        new
                        {
                            Id = 19,
                            ContribuyenteId = 3,
                            Itbis18 = 180m,
                            Monto = 1000m,
                            Ncf = "E310000000019",
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            rncCedula = "123876879"
                        },
                        new
                        {
                            Id = 20,
                            ContribuyenteId = 3,
                            Itbis18 = 36m,
                            Monto = 200m,
                            Ncf = "E310000000020",
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            rncCedula = "123876879"
                        },
                        new
                        {
                            Id = 21,
                            ContribuyenteId = 3,
                            Itbis18 = 180m,
                            Monto = 1000m,
                            Ncf = "E310000000021",
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            rncCedula = "123876879"
                        },
                        new
                        {
                            Id = 22,
                            ContribuyenteId = 3,
                            Itbis18 = 36m,
                            Monto = 200m,
                            Ncf = "E310000000022",
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            rncCedula = "123876879"
                        },
                        new
                        {
                            Id = 23,
                            ContribuyenteId = 3,
                            Itbis18 = 180m,
                            Monto = 1000m,
                            Ncf = "E310000000023",
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            rncCedula = "123876879"
                        });
                });

            modelBuilder.Entity("DGII.BOL.Models.Contribuyente", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("rncCedula")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.HasKey("Id", "rncCedula");

                    b.HasIndex("EstadoId");

                    b.HasIndex("TipoId");

                    b.ToTable("Contribuyentes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            rncCedula = "98754321012",
                            EstadoId = 1,
                            Nombre = "JUAN PEREZ",
                            TipoId = 1,
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            rncCedula = "123456789",
                            EstadoId = 2,
                            Nombre = "FARMACIA TU SALUD",
                            TipoId = 2,
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            rncCedula = "123876879",
                            EstadoId = 1,
                            Nombre = "Jose Perez",
                            TipoId = 1,
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            rncCedula = "89239473",
                            EstadoId = 2,
                            Nombre = "COLMADO FULANITO",
                            TipoId = 2,
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            rncCedula = "1245484796",
                            EstadoId = 1,
                            Nombre = "EDDY GRULLON",
                            TipoId = 1,
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            rncCedula = "56677867866",
                            EstadoId = 2,
                            Nombre = "DGII",
                            TipoId = 2,
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            rncCedula = "5567733467",
                            EstadoId = 1,
                            Nombre = "CARLOS MENA",
                            TipoId = 1,
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            rncCedula = "5611675673",
                            EstadoId = 2,
                            Nombre = "MARIANO TERRERO",
                            TipoId = 2,
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            rncCedula = "3111245454",
                            EstadoId = 1,
                            Nombre = "EDWARD CRUZ",
                            TipoId = 1,
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            rncCedula = "4442888566",
                            EstadoId = 2,
                            Nombre = "LA SIRENA",
                            TipoId = 2,
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            rncCedula = "45345345236",
                            EstadoId = 1,
                            Nombre = "DIANA RIVAS",
                            TipoId = 1,
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            rncCedula = "66565657443",
                            EstadoId = 2,
                            Nombre = "SALON JOSEFINA",
                            TipoId = 2,
                            fechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DGII.BOL.Models.EstadoContribuyente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Activo"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Inactivo"
                        });
                });

            modelBuilder.Entity("DGII.BOL.Models.TipoContribuyente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tipos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "PERSONA FISICA"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "PERSONA JURIDICA"
                        });
                });

            modelBuilder.Entity("DGII.BOL.Models.Comprobante", b =>
                {
                    b.HasOne("DGII.BOL.Models.Contribuyente", "Contribuyente")
                        .WithMany("Comprobantes")
                        .HasForeignKey("ContribuyenteId", "rncCedula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contribuyente");
                });

            modelBuilder.Entity("DGII.BOL.Models.Contribuyente", b =>
                {
                    b.HasOne("DGII.BOL.Models.EstadoContribuyente", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DGII.BOL.Models.TipoContribuyente", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("DGII.BOL.Models.Contribuyente", b =>
                {
                    b.Navigation("Comprobantes");
                });
#pragma warning restore 612, 618
        }
    }
}
